### ISSUE TITLE
Setup the repo

### ISSUE THREAD

**Issue by Vlasakh** [nedosika/filmoteka#19]
1. Deny all the merge strategies but the "Squash and merge" 
![image](https://user-images.githubusercontent.com/23474972/158014101-aaea74d7-f43b-49ce-b37d-dc91240ba577.png)
2. Delete branch automatically
![image](https://user-images.githubusercontent.com/23474972/158014167-3e98b01c-6932-43f4-aff9-0faf3781ebb0.png)

**Comment by nedosika** [comment]
![image](https://user-images.githubusercontent.com/11612434/158031657-e6a28672-c832-43cc-8b93-a0d53e074d6b.png)
